version: '3'
services:
  mail:
    container_name: mail-sec22
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 25:25
  ssh:
    container_name: ssh-sec2
    image: rastasheep/ubuntu-sshd
    ports:
      - 2222:22